apiVersion: v1
kind: Namespace
metadata:
  name: securebank
  labels:
    name: securebank
    environment: production
    # âŒ Advertising sensitive data
    contains-pci-data: "true"
    security-level: "insecure"